version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-patch" ]
    - dependency-name: "typing-extensions"
      update-types: [ "version-update:semver-minor" ]
    # Update these dependencies with python-template or `poetry update`
    - dependency-name: "omegaconf"
    # Make group
    - dependency-name: "black"
    - dependency-name: "isort"
    - dependency-name: "pycln"
    - dependency-name: "doc8"
    - dependency-name: "mypy"
    - dependency-name: "flake8"
    - dependency-name: "flake8-docstrings"
    - dependency-name: "flake8-ensure-ascii"
    - dependency-name: "pydocstyle"
    - dependency-name: "safety"
    - dependency-name: "cruft"
    - dependency-name: "lice"
    - dependency-name: "pre-commit"
    # Tests group
    - dependency-name: "pytest"
    - dependency-name: "pytest-cov"
    - dependency-name: "pytest-mock"
    - dependency-name: "pytest-testmon"
    - dependency-name: "pytest-randomly"
    - dependency-name: "Faker"
    # Docs group
    - dependency-name: "sphinx"
    - dependency-name: "sphinx-autodoc-typehints"
    - dependency-name: "sphinx-autoapi"
    - dependency-name: "sphinx-intl"
    - dependency-name: "furo"
    - dependency-name: "m2r2"
    - dependency-name: "tomli"
    - dependency-name: "packaging"
    # GitHub Hooks group
    - dependency-name: "requests"
    - dependency-name: "GitPython"
    # Types group
    - dependency-name: "types-markdown"
    - dependency-name: "types-decorator"
    - dependency-name: "types-mock"
    - dependency-name: "types-protobuf"
    - dependency-name: "types-requests"
    - dependency-name: "types-setuptools"
    - dependency-name: "types-waitress"

- package-ecosystem: pip
  directory: "/czech_plus/_vendor"
  schedule:
    interval: daily
    time: "00:00"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
